version: 2.1

jobs:
  build:
    docker:
        - image: circleci/node:12.16
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Running integration tests
          command: |
            npm run test
